name = "glaze_oat"
version = "1.0.0"
description = "ğŸ© Lustre Bindings to Oat UI Components"

licences = ["MIT"]
repository = { type = "github", user = "daniellionel01", repo = "glaze", path = "glaze_oat" }

links = [
  { title = "Oat", href = "https://oat.ink/" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
